### PR TITLE
Fixes to Hsqldb driver

### PR DESCRIPTION
**Pull request by lJoublanc**
Fix bug where offset not handled when date day has leading zero.
Refactor hour and hour-offset handling.
Sql type is no longer Other
Use max supported precision instead of 3 fractional secs.

### CODE REVIEW

**Comment by lJoublanc** [comment]
Hi Xavier, this is my first (ever) pull request so I apologize in advance of any github protocol transgression! Please bear with me and feel free to point out if I'm doing anything wrong ...

First off thanks for your contribution, having the java8 primitives makes a world of difference to me as I need to work with timezoned data all the time.

I've fixed a bug that arises because of the handling for specific hsqldb string formats for time. The following will fail:

`Exception in thread "main" java.time.format.DateTimeParseException: Text '1970-01-001 01:00:00.000000' could not be parsed at index 10`

Note the extra zero in the day. Because it's searching for the zero offset prefix as Z/+/-, and the minus followed by a zero can appear in the date.

Also, not sure if the sql type was supposed to be `Other` - I've set it to the respective type. You may want to do the same for other drivers?

Finally, I changed  the precision to maximum supported precision (from 3), because as far as I'm aware this wont' have any effect on the storage requirements or efficiency; in java the  internal representation is a triplet of ordinal second, nano-of-second, and offset. And on disk it's stored as a string, as far as I'm aware, so omitted fractions-of-second just won't be stored.

**Comment by xavier-fernandez** [comment]
Hi @lJoublanc, eveything in the PR LGTM.
Thank you a lot :)

**Comment by xavier-fernandez** [comment]
Hi @lJoublanc, the commit looks good at the first glimpse, I rebased everything to master, and I runned the Travis, but the build is failing now with your commit:

https://travis-ci.org/slick/slick/builds/163998667

Thank you a lot :)

**Comment by lJoublanc** [comment]
I think I've resolved the issue. The tests pass locally on my machine at least. I also saw your message about the license, will sign as soon as I have access to my personal mail ...

**Comment by xavier-fernandez** [comment]
Can you send another PR? Against xavier-fernandez/master?
Thank you a lot :)

**Comment by lJoublanc** [comment]
Done. the merge looks huge - I don't know if I've cocked something up or whether it's because you rebased your branch. You should see only three lines of changes, so let me know if I've done something wrong and I'll try to rebase my own repository first.

**Comment by xavier-fernandez** [comment]
@lJoublanc, you should rebase the whole repository first :|
Thank you a lot for your effort, your help is really helpful :)

**Pull request merged**
